"""cria tabelas iniciais: casas, inquilinos, contratos, parcelas, pagamentos

Revision ID: 1ff3ff34b393
Revises: 
Create Date: 2026-09-07 21:41:21.956775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff3ff34b393'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('endereco', sa.String(), nullable=False),
    sa.Column('valor_referencia', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inquilinos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contratos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('casa_id', sa.UUID(), nullable=False),
    sa.Column('inquilino_id', sa.UUID(), nullable=False),
    sa.Column('valor_aluguel', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dia_vencimento', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim_prevista', sa.Date(), nullable=False),
    sa.Column('data_fim_real', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'ENCERRADO', name='statuscontrato'), nullable=False),
    sa.ForeignKeyConstraint(['casa_id'], ['casas.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilinos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contrato_id', sa.UUID(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcelas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contrato_id', sa.UUID(), nullable=False),
    sa.Column('mes_referencia', sa.String(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('valor_esperado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamento_parcelas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pagamento_id', sa.UUID(), nullable=False),
    sa.Column('parcela_id', sa.UUID(), nullable=False),
    sa.Column('valor_alocado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pagamento_id'], ['pagamentos.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamento_parcelas')
    op.drop_table('parcelas')
    op.drop_table('pagamentos')
    op.drop_table('contratos')
    op.drop_table('inquilinos')
    op.drop_table('casas')
    # ### end Alembic commands ###
